[package]
name = "ruscomp"
version = "0.1.0"
edition = "2021"

[lib]
name = "ruscomp"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.25", features = ["extension-module"] }
bitvec = "1.0"
